import { MenuItem } from "./types";

export const demoMenuItems: MenuItem[] = [
  {
    itemId: 1,
    itemName: "Butter Chicken",
    restId: 0,
    itemPrice: "12.99",
    itemDescription:
      "Tender chicken pieces in a rich, creamy tomato-based curry sauce",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 2,
    itemSpiceLevel: 4,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: false,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "non-veg",
  },
  {
    itemId: 2,
    itemName: "Paneer Tikka",
    restId: 0,
    itemPrice: "9.99",
    itemDescription:
      "Grilled cottage cheese cubes marinated in spices and yogurt",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 3,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "veg",
  },
  {
    itemId: 3,
    itemName: "Gulab Jamun",
    restId: 0,
    itemPrice: "5.99",
    itemDescription:
      "Sweet milk-solid balls soaked in rose-flavored sugar syrup",
    itemSweet: true,
    itemSpicy: false,
    itemSweetLevel: 5,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImage: "/DummyDishImage.jpg",
    category: "desserts",
  },
  {
    itemId: 4,
    itemName: "Veg Biryani",
    restId: 0,
    itemPrice: "11.99",
    itemDescription:
      "Fragrant basmati rice cooked with mixed vegetables and aromatic spices",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 3,
    itemAvailable: false,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "veg",
  },
  {
    itemId: 5,
    itemName: "Chicken Tikka Masala",
    restId: 0,
    itemPrice: "13.99",
    itemDescription: "Grilled chicken in a creamy, spiced tomato-based curry",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 2,
    itemSpiceLevel: 4,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: false,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "non-veg",
  },
  {
    itemId: 6,
    itemName: "Mango Lassi",
    restId: 0,
    itemPrice: "4.99",
    itemDescription: "Sweet yogurt drink with mango pulp",
    itemSweet: true,
    itemSpicy: false,
    itemSweetLevel: 4,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImage: "/DummyDishImage.jpg",
    category: "drinks",
  },
  {
    itemId: 7,
    itemName: "Masala Chai",
    restId: 0,
    itemPrice: "3.99",
    itemDescription: "Traditional spiced Indian tea with milk",
    itemSweet: true,
    itemSpicy: true,
    itemSweetLevel: 3,
    itemSpiceLevel: 2,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "drinks",
  },
  {
    itemId: 8,
    itemName: "Rasmalai",
    restId: 0,
    itemPrice: "6.99",
    itemDescription: "Soft cottage cheese dumplings in sweetened milk",
    itemSweet: true,
    itemSpicy: false,
    itemSweetLevel: 5,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImage: "/DummyDishImage.jpg",
    category: "desserts",
  },
  {
    itemId: 9,
    itemName: "Vegetable Samosa",
    restId: 0,
    itemPrice: "4.50",
    itemDescription: "Crispy pastry filled with spiced potatoes and peas",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 2,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "appetizers",
  },
  {
    itemId: 10,
    itemName: "Tomato Soup",
    restId: 0,
    itemPrice: "5.00",
    itemDescription: "Classic creamy tomato soup",
    itemSweet: true,
    itemSpicy: false,
    itemSweetLevel: 3,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImage: "/DummyDishImage.jpg",
    category: "soups",
  },
  {
    itemId: 11,
    itemName: "Garden Salad",
    restId: 0,
    itemPrice: "7.50",
    itemDescription: "Fresh mixed greens with cucumber, tomatoes, and carrots",
    itemSweet: false,
    itemSpicy: false,
    itemSweetLevel: 0,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImage: "/DummyDishImage.jpg",
    category: "salads",
  },
  {
    itemId: 12,
    itemName: "Fish Curry",
    restId: 0,
    itemPrice: "15.50",
    itemDescription: "Fish cooked in a spicy coconut milk-based curry",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 4,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: false,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "non-veg",
  },
  {
    itemId: 13,
    itemName: "Lamb Vindaloo",
    restId: 0,
    itemPrice: "16.00",
    itemDescription: "Spicy lamb curry with vinegar and potatoes",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 5,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: false,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "non-veg",
  },
  {
    itemId: 14,
    itemName: "Palak Paneer",
    restId: 0,
    itemPrice: "10.50",
    itemDescription: "Cottage cheese in a spinach-based gravy",
    itemSweet: false,
    itemSpicy: true,
    itemSweetLevel: 1,
    itemSpiceLevel: 2,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImage: "/DummyDishImage.jpg",
    category: "veg",
  },
];
