import { MenuItem } from "./types";

export const demoMenuItems: MenuItem[] = [
  // Restaurant Menu Items (restId: 1)
  {
    itemId: 101,
    itemName: "Butter Chicken",
    restId: 1,
    itemPrice: "16.99",
    itemDescription:
      "Tender chicken pieces in a rich, creamy tomato-based curry sauce with butter and aromatic spices",
    itemSweet: false,
    itemSpicy: true,
    itemSpiceLevel: 3,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: false,
    itemIsJain: false,
    itemImages: [
      "/DummyDishImage.jpg",
      "/DummyDishImage2.jpg",
      "/DummyDishImage3.jpg",
    ],
    category: "main-course",
    ingredients: ["Chicken", "Tomato", "Cream", "Butter", "Spices"],
    itemIngredients: "Chicken, Tomato, Cream, Butter, Spices",
  },
  {
    itemId: 102,
    itemName: "Paneer Tikka",
    restId: 1,
    itemPrice: "12.99",
    itemDescription:
      "Grilled cottage cheese cubes marinated in spices and yogurt, served with mint chutney",
    itemSweet: false,
    itemSpicy: true,
    itemSpiceLevel: 3,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg", "/DummyDishImage2.jpg"],
    category: "starters",
    ingredients: ["Paneer", "Yogurt", "Spices", "Bell Peppers", "Onion"],
    itemIngredients: "Paneer, Yogurt, Spices, Bell Peppers, Onion",
  },
  {
    itemId: 103,
    itemName: "Veg Biryani",
    restId: 1,
    itemPrice: "14.99",
    itemDescription:
      "Fragrant basmati rice cooked with mixed vegetables and aromatic spices",
    itemSweet: false,
    itemSpicy: true,
    itemSpiceLevel: 3,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg", "/DummyDishImage3.jpg"],
    category: "main-course",
    ingredients: ["Basmati Rice", "Mixed Vegetables", "Spices", "Saffron"],
    itemIngredients: "Basmati Rice, Mixed Vegetables, Spices, Saffron",
  },
  {
    itemId: 104,
    itemName: "Gulab Jamun",
    restId: 1,
    itemPrice: "6.99",
    itemDescription:
      "Sweet milk-solid balls soaked in rose-flavored sugar syrup",
    itemSweet: true,
    itemSpicy: false,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImages: ["/DummyDishImage.jpg"],
    category: "desserts",
    ingredients: ["Milk Solids", "Sugar", "Rose Water", "Cardamom"],
    itemIngredients: "Milk Solids, Sugar, Rose Water, Cardamom",
  },
  {
    itemId: 105,
    itemName: "Masala Chai",
    restId: 1,
    itemPrice: "3.99",
    itemDescription:
      "Traditional spiced Indian tea with milk and aromatic spices",
    itemSweet: true,
    itemSpicy: true,
    itemSpiceLevel: 2,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg"],
    category: "beverages",
    ingredients: ["Tea", "Milk", "Ginger", "Cardamom", "Cinnamon"],
    itemIngredients: "Tea, Milk, Ginger, Cardamom, Cinnamon",
  },

  // Cafe Menu Items (restId: 2)
  {
    itemId: 201,
    itemName: "Avocado Toast",
    restId: 2,
    itemPrice: "8.99",
    itemDescription:
      "Sourdough toast topped with smashed avocado, cherry tomatoes, and microgreens",
    itemSweet: false,
    itemSpicy: false,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg"],
    category: "breakfast",
    ingredients: [
      "Sourdough Bread",
      "Avocado",
      "Cherry Tomatoes",
      "Microgreens",
      "Olive Oil",
    ],
    itemIngredients:
      "Sourdough Bread, Avocado, Cherry Tomatoes, Microgreens, Olive Oil",
  },
  {
    itemId: 202,
    itemName: "Cappuccino",
    restId: 2,
    itemPrice: "4.50",
    itemDescription: "Espresso with steamed milk and a thick layer of foam",
    itemSweet: false,
    itemSpicy: false,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: true,
    itemImages: ["/DummyDishImage.jpg"],
    category: "coffee",
    ingredients: ["Espresso", "Steamed Milk", "Milk Foam"],
    itemIngredients: "Espresso, Steamed Milk, Milk Foam",
  },
  {
    itemId: 203,
    itemName: "Chocolate Croissant",
    restId: 2,
    itemPrice: "5.99",
    itemDescription: "Buttery, flaky croissant filled with rich chocolate",
    itemSweet: true,
    itemSpicy: false,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: true,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg"],
    category: "pastries",
    ingredients: ["Butter", "Flour", "Chocolate", "Yeast", "Sugar"],
    itemIngredients: "Butter, Flour, Chocolate, Yeast, Sugar",
  },
  {
    itemId: 204,
    itemName: "Quinoa Bowl",
    restId: 2,
    itemPrice: "12.99",
    itemDescription:
      "Healthy bowl with quinoa, roasted vegetables, avocado, and tahini dressing",
    itemSweet: false,
    itemSpicy: false,
    itemSpiceLevel: 1,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: false,
    itemImages: ["/DummyDishImage.jpg"],
    category: "lunch",
    ingredients: ["Quinoa", "Mixed Vegetables", "Avocado", "Tahini", "Lemon"],
    itemIngredients: "Quinoa, Mixed Vegetables, Avocado, Tahini, Lemon",
  },
  {
    itemId: 205,
    itemName: "Matcha Latte",
    restId: 2,
    itemPrice: "5.50",
    itemDescription:
      "Premium matcha green tea powder whisked with steamed milk",
    itemSweet: true,
    itemSpicy: false,
    itemSpiceLevel: 0,
    itemAvailable: true,
    itemBestSeller: false,
    itemIsVeg: true,
    itemIsJain: true,
    itemImages: ["/DummyDishImage.jpg"],
    category: "coffee",
    ingredients: ["Matcha Powder", "Steamed Milk", "Honey"],
    itemIngredients: "Matcha Powder, Steamed Milk, Honey",
  },
];
